# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
language: java
dist: trusty
sudo: required
env:
  global:
    - MAVEN_HOME: "${TRAVIS_BUILD_DIR}/maven"
    - STAGING_DIR: "${TRAVIS_BUILD_DIR}/gh-pages"
    - GH_REF: github.com/aajisaka/hadoop-document.git
    - secure: "GuExArhOg4mCgctdv1y+KU9Udv/anWlrSjftNVLpXW8DPTdcQN1YVJTjUAWHyRK8gb2lua9yhiPw1YapovvZJhLY8CMRxZZE4XOxm2ujSBVT21Z8tjQpW2qkx9FlJR1obLHO9hLpmpRzu5ITU4+9mYDCrfQgpIU01JIg+hPiwQ+oNH14fzI9fy1ffINCP8YKwQgK7wwZ5Wz9pm8ioWjEGu+NgrsV3ofPSv1HGbgNbKq7x4BSirWtWQ5GBQUlytnofDr6tk5npan5nVofY+0x2bkdnU4QPBOwK0q//obVvcdEum0qXsvwRvNUQu4Au4wh7f6nSyzPTm5UPRYEMGUMLoa24gPSeUu0oPSbs57VxYhrf+izGj1JQOEg9i5w5g7Fr+TM3f+FhtRE0jgCpPaHnsm+gUzpf4cATwN5T9B2Fy4hCWxVGcjDZeKEA9Si5UIkW5CyGDxz4WMsVB22w2xt1HCLYx5CRH6HvhyFE+FT64j0ppWb33alga2TOx9TPpG8oz13TmqiS12vTt5QVYGmXaGmBvAVUfgg8fL6xj9tklbS4KNv5NzPkME/IsF+spLFMHVGXaLap3tlBERNUjnx2Qyj2jk7LjIW7GoJlp6etJmgCAV66A7injEozKKHIUxaDshOUKKDMB8ECJvJ/yXY9NjXSvk2JCTmi/fPxPy2PE0="
cache:
  directories:
    - $HOME/.m2
before_install:
 - sudo apt-get install -y protobuf-compiler
before_script:
 - mkdir -p ${MAVEN_HOME}
 - curl -L -s -S http://www-us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz -o maven.tar.gz
 - tar xzf maven.tar.gz --strip-components 1 -C ${MAVEN_HOME}/
 - export PATH=${MAVEN_HOME}/bin:${PATH}
 - git clone --depth 1 https://github.com/apache/hadoop.git
 - cd hadoop
script:
 - which mvn
 - ls -alh ${MAVEN_HOME}/bin
 - cd hadoop-maven-plugins
 - mvn -B -q install
 - cd ..
 - mvn -B site
 - mvn -B -q site:stage -DstagingDirectory=${STAGING_DIR}
 - cd ..
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
