---
language: java
dist: trusty
sudo: required
env:
  global:
    - GH_REF: github.com/aajisaka/hadoop-document.git
    - secure: "GuExArhOg4mCgctdv1y+KU9Udv/anWlrSjftNVLpXW8DPTdcQN1YVJTjUAWHyRK8gb2lua9yhiPw1YapovvZJhLY8CMRxZZE4XOxm2ujSBVT21Z8tjQpW2qkx9FlJR1obLHO9hLpmpRzu5ITU4+9mYDCrfQgpIU01JIg+hPiwQ+oNH14fzI9fy1ffINCP8YKwQgK7wwZ5Wz9pm8ioWjEGu+NgrsV3ofPSv1HGbgNbKq7x4BSirWtWQ5GBQUlytnofDr6tk5npan5nVofY+0x2bkdnU4QPBOwK0q//obVvcdEum0qXsvwRvNUQu4Au4wh7f6nSyzPTm5UPRYEMGUMLoa24gPSeUu0oPSbs57VxYhrf+izGj1JQOEg9i5w5g7Fr+TM3f+FhtRE0jgCpPaHnsm+gUzpf4cATwN5T9B2Fy4hCWxVGcjDZeKEA9Si5UIkW5CyGDxz4WMsVB22w2xt1HCLYx5CRH6HvhyFE+FT64j0ppWb33alga2TOx9TPpG8oz13TmqiS12vTt5QVYGmXaGmBvAVUfgg8fL6xj9tklbS4KNv5NzPkME/IsF+spLFMHVGXaLap3tlBERNUjnx2Qyj2jk7LjIW7GoJlp6etJmgCAV66A7injEozKKHIUxaDshOUKKDMB8ECJvJ/yXY9NjXSvk2JCTmi/fPxPy2PE0="
cache:
  directories:
    - $HOME/.m2
before_install:
 - sudo apt-get install -y protobuf-compiler
before_script:
 - export PWD=`pwd`
 - git clone --depth 1 https://github.com/apache/hadoop.git
 - cd hadoop
script:
 - cd hadoop-maven-plugins
 - mvn -B -q install
 - cd ..
 - mvn -B -q site -Dmaven.javadoc.skip=true
 - mvn -B -q site:stage -DstagingDirectory=${PWD}/gh-pages
deploy:
 - cd ${PWD}/gh-pages
 - git init
 - git config --global user.email "aajisaka@apache.org"
 - git config --global user.name "Akira Ajisaka"
 - git add -A
 - git commit -m "Automatic deploy to GitHub pages"
 - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
