# This is a basic workflow to help you get started with Actions
name: deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Run daily
  schedule:
    - cron: '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Apache Hadoop
        uses: actions/checkout@v2
        with:
          repository: apache/hadoop
          path: hadoop
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Need to build maven plugins first
      - name: Build Hadoop maven plugins
        run: cd ~/hadoop/hadoop-maven-plugin && mvn --batch-mode --quiet install && cd ..
      - name: Build Hadoop
        run: mvn --batch-mode --quiet install -DskipTests -DskipShade
      - name: Build document
        run: mvn --batch-mode site
      - name: Aggregate the document
        run: mvn --batch-mode --quiet site:stage -DstagingDirectory=staging
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ~/hadoop/staging
